# -*- coding: utf-8 -*-
"""Data_set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyu33DBYKCglCCOgQxDWxgSQ3rzrG9jh
"""

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

df=pd.read_excel('/content/Realestate_data.csv.xlsx')

print(df.head())

print(df.info())

#data cleaning
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print(df.columns.tolist())
df = df.drop_duplicates()

#categorical cleaning
df['status'] = df['status'].str.strip().str.lower()
df['flat_type'] = df['flat_type'].str.strip().str.lower()
df['locality'] = df['locality'].str.strip().str.lower()

df=df.drop_duplicates()
print(df)

from numpy import cos
# Question 1 : which is the costliest flat among all ?
costliest_flat = df.loc[df['price'].idxmax()]
print(f"The costliest flat is {costliest_flat['property_type']}, located at {costliest_flat['locality']}\n with a price of {costliest_flat['price']}.")

# Question 2 : which locatlity has the highest flats listed?
highest_listed_locality = df['locality'].value_counts().idxmax()
print(f"The locality with the highest number of listed flats is {highest_listed_locality}.")

# Question 3 : which locality has the highest average price?
highest_avg_price_locality = df.groupby('locality')['price'].mean().idxmax()
print(f"The locality with the highest average price is {highest_avg_price_locality}.")

# Question 3 : Which locality has the highest rate per square foot?
df['rate_per_sqft'] = df['price'] / df['area']
highest_rate_sqft_locality = df.groupby('locality')['rate_per_sqft'].mean().idxmax()
print(f"The locality with the highest rate per square foot is {highest_rate_sqft_locality}.")

# Question 4 : Do ready-to-move properties cost more than under-construction properties?
avg_price_ready_to_move = df[df['status'] == 'ready_to_move']['price'].mean()
avg_price_under_construction = df[df['status'] == 'under_construction']['price'].mean()
if avg_price_ready_to_move > avg_price_under_construction:
    print("Ready-to-move properties cost more than under-construction properties.")
else:
    print("Ready-to-move properties do not cost more than under-construction properties.")

# Question 5 : Do RERA-approved properties command a price premium?
avg_price_rera_approved = df[df['rera_approval'] == 'True']['price'].mean()
avg_price_rera_not_approved = df[df['rera_approval'] == 'Not TRUE']['price'].mean()
if avg_price_rera_approved > avg_price_rera_not_approved:
    print("RERA-approved properties command a price premium.")
else:
    print("RERA-approved properties do not command a price premium")

# Question 6 : How does area (sqft) impact property price?
sns.scatterplot(x='area', y='price', data=df)
plt.xlabel('Area (sqft)')
plt.ylabel('Price')
plt.title('Area vs Price')
plt.show()

# Question 7: Which BHK configuration is the most expensive on average?
df['bhk'] = df['property_type'].str.extract(r'(\d+)\s*BHK')


df['bhk'] = pd.to_numeric(df['bhk'])

avg_price_by_bhk = df.groupby('bhk')['price'].mean()

if not avg_price_by_bhk.empty:
    most_expensive_bhk = avg_price_by_bhk.idxmax()
    print(f"The BHK configuration with the highest average price is {int(most_expensive_bhk)} BHK.")
else:
    print("No BHK data found in the property_type column.")

# Question 8: Which property type (Apartment, Floor, Plot) is the costliest?
avg_price_by_property_type = df.groupby('property_type')['price'].mean()
if not avg_price_by_property_type.empty:
    costliest_property_type = avg_price_by_property_type.idxmax()
    print(f"The property type with the highest average price is {costliest_property_type}.")

# Question 9: Do certain builders or companies consistently price higher?
avg_price_by_builder = df.groupby('builder_name')['price'].mean()
if not avg_price_by_builder.empty:
    most_expensive_builder = avg_price_by_builder.idxmax()
    print(f"The builder with the highest average price is {most_expensive_builder}.")

# Question 10 : Are larger homes always more expensive per square foot?
df['area_per_sqft'] = df['area'] / df['price']
sns.scatterplot(x='area_per_sqft', y='price', data=df)
plt.xlabel('Area per Square Foot')
plt.ylabel('Price')
plt.title('Area per Square Foot vs Price')
plt.show()